language: java
jdk:
    - openjdk8
    - openjdk11
branches:
  only:
    - master
before_install:
  - pwd
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh -O $TRAVIS_BUILD_DIR/install-jdk.sh
  - chmod u+x $TRAVIS_BUILD_DIR/install-jdk.sh
  - $TRAVIS_BUILD_DIR/install-jdk.sh --feature 11 --target $TRAVIS_BUILD_DIR/openjdk11
  - ls $TRAVIS_BUILD_DIR
  - ls /usr/lib/jvm
  - cp ./toolchains.xml ~/.m2/
script: "mvn clean package -P travis"
after_success:
  - mvn clean test jacoco:report coveralls:report
